- hosts: 
  gather_facts: no
  vars: 
      bootstrap_id: "{{lookup('file','playbooks/id_secret/bootstrap_id.txt')}}"
      cluster_secret: "{{lookup('file', 'playbooks/id_secret/cluster_secret.txt')}}"
  
  tasks:
    - name: Make IPFSCluster folder
      shell: mkdir -p IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service

    - name: Make IPFSCluster control folder
      shell: mkdir -p IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-ctl

    - name: Copying IPFSCluster service binary
      copy:
        src: playbooks/kubo/ipfs-cluster-service/ipfs-cluster-service
        dest: IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/ipfs-cluster-service

    - name: Copying IPFSCluster ctl binary
      copy:
        src: playbooks/kubo/ipfs-cluster-ctl/ipfs-cluster-ctl
        dest: IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-ctl/ipfs-cluster-ctl

    - name: Authorize execution of IPFSCluster ctl binary
      shell: chmod u+x IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-ctl/ipfs-cluster-ctl

    - name: Authorize execution of IPFSCluster binary
      shell: chmod u+x IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/ipfs-cluster-service

    - name: Initiliaze IPFSCluster
      shell: IPFS_CLUSTER_PATH=IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/.ipfs-cluster IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/ipfs-cluster-service init --consensus crdt 

    - name: Add bootstrap to peerstore
      shell: echo "{{ bootstrap_id }}" > IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/.ipfs-cluster/peerstore

    - name: Copy python script for secret edition
      copy:
        src: playbooks/kubo/cluster_secret_adder.py
        dest: IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/.ipfs-cluster/cluster_secret_adder.py

    - name: authorize execution of python secret adder
      shell: chmod u+x IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/.ipfs-cluster/cluster_secret_adder.py

    - name: Change cluster secret
      shell: python3 IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/.ipfs-cluster/cluster_secret_adder.py {{ cluster_secret }} IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/.ipfs-cluster/service.json

    - name: Start IPFSCluster
      shell: IPFS_CLUSTER_PATH=IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/.ipfs-cluster nohup IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/ipfs-cluster-service daemon >/dev/null 2>&1 &
