global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: node_exporter
  static_configs:
  - targets:
    - ip1:9100
    - ip2:9100
