#################################################################
#    ANSIBLE PLAYBOOK - IPFS AND IPFSCLUSTER LAUNCHER           #
#                                                               #
# To start network : (will ask for ssh password)                #
# ansible-playbook playbook.yml -i hosts.ini --ask-pass         #
#################################################################                                                               


# STARTING IPFS AND IPFSCLUSTER NETWORKS

- hosts: IPFS-nodes
  gather_facts: no
  tasks:
    - name: Start IPFS
      shell: IPFS_PATH=./IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/kubo/.ipfs ./IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs daemon —enable-gc &


- hosts: IPFScluster-nodes
    gather_facts: no
    tasks:
      - name: Start IPFScluster
      shell: IPFS_CLUSTER_PATH=./IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/.ipfs-cluster ./ipfs-cluster-service daemon &
    
#STARTING DATA COLLECTION SYSTEM

- hosts: IPFScluster-nodes
    gather_facts: no
    tasks:
      - name: Starting python data collection programs
      shell: python3 ./IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/data-collection-node.py

- hosts: datacollector
      gather_facts: no
      tasks:
        - name : Starting data collector 

# Pausing playbook while data is being collected

- name: Pause for 10 seconds
  hosts: localhost
  connection: local
  tasks:
    - name: Pause for 10 seconds
      pause:
        seconds: 10 #CHANGE VALUE TO CHANGE TEST LENGTH


#SHUTTING DOWN BOTH NETWORKS

- hosts: IPFScluster-nodes
  gather_facts: no
  tasks:
    - name: Kill IPFS network
      shell: killall ipfs-cluster-service
      register: command_output
    - name: Display outputs
      debug: var=command_output.stdout_lines


- hosts: IPFS-nodes
  gather_facts: no
  tasks:
    - name: Kill IPFS network
      shell: killall ipfs
      register: command_output
    - name: Display outputs
      debug: var=command_output.stdout_lines

