#SHUTTING DOWN BOTH NETWORKS

# - hosts: IPFScluster-nodes
#   gather_facts: no
#   tasks:
#     - name: Kill IPFS network
#       shell: killall ipfs-cluster-service
#       register: command_output
#     - name: Display outputs
#       debug: var=command_output.stdout_lines


- hosts: IPFS-nodes
  gather_facts: no
  tasks:
    - name: Kill IPFS network
      shell: killall ipfs
      register: command_output
    - name: Kill data collectors
      shell: killall python3
    - name: Display outputs
      debug: var=command_output.stdout_lines

- hosts: datacollector
  gather_facts: no
  tasks:
  - name: Kill data aggregator
    shell: killall python3
    register: command_output
  - name: Display outputs
    debug: var=command_output.stdout_lines