#################################################################
#    ANSIBLE PLAYBOOK - IPFS AND IPFSCLUSTER LAUNCHER           #
#                                                               #
# To start network : (will ask for ssh password)                #
# ansible-playbook playbook-u.yml -i hosts.ini --ask-pass       #
#################################################################                                                               


# STARTING IPFS AND IPFSCLUSTER NETWORKS

- hosts: IPFS-nodes
  gather_facts: no
  tasks:
    - copy:
        src: to_copy/data-collection-node.py
        dest: IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/data-collection-node.py
    - name: Start IPFS dameons
      shell: "IPFS_PATH=IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/kubo/.ipfs nohup IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/kubo/ipfs daemon --enable-gc >/dev/null 2>&1 &"
    - name: Start data collector 
      shell: nohup python3 IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/data-collection-node.py {{ hostvars[inventory_hostname]['label_ip'] }} >/dev/null 2>&1 &

- hosts: IPFScluster-nodes
  gather_facts: no
  tasks:
    - name : Start IPFSCluster daemons
      shell: IPFS_CLUSTER_PATH=IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/.ipfs-cluster nohup IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/ipfs-cluster-service/ipfs-cluster-service daemon >/dev/null 2>&1 &

- hosts: datacollector
  gather_facts: no
  tasks:
    - copy:
        src: hosts.ini
        dest: IPFS_nodes/data-node/hosts.ini
    - name: Start data aggregator
      shell: nohup python3 IPFS_nodes/data-node/data-collection-central.py >/dev/null 2>&1 &
