- name: Get size of "blocks" dir
  shell: du -sh IPFS_nodes/{{ hostvars[inventory_hostname]['label'] }}/kubo/.ipfs/blocks 
  register: command_output
- name: Write to local log
  shell : echo "{{ hostvars[inventory_hostname]['label'] }} -- {{ command_output.stdout }} \n" >> blocks.txt
  delegate_to: localhost